03/31/2016 06:46:41 PM - INFO - Logger initialized
03/31/2016 06:46:41 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:46:41 PM - INFO - Controller turned off successfully.
03/31/2016 06:46:41 PM - INFO - Turning on sta3800 controller.
03/31/2016 06:46:41 PM - INFO - Controller turned on successfully.
03/31/2016 06:46:52 PM - INFO - Data directory changed to /Users/adamsnyder/ccdcontroller/test_dir
03/31/2016 06:46:54 PM - INFO - Starting 4.0s exp image with filebase /Users/adamsnyder/ccdcontroller/test_dir/Hello.exp.4.0s.
03/31/2016 06:46:54 PM - ERROR - Executable exp_acq. not found. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 178, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 112, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
03/31/2016 06:47:03 PM - INFO - Turning off sta3800 controller
03/31/2016 06:47:03 PM - INFO - Controller turned off successfully
03/31/2016 07:42:09 PM - INFO - GUI display widget values succesfully restored.
03/31/2016 07:42:09 PM - INFO - Turning off sta3800 controller.
03/31/2016 07:42:09 PM - INFO - Controller turned off successfully.
03/31/2016 07:42:09 PM - INFO - Turning on sta3800 controller.
03/31/2016 07:42:09 PM - INFO - Controller turned on successfully.
03/31/2016 07:42:14 PM - INFO - Turning off sta3800 controller
03/31/2016 07:42:14 PM - INFO - Controller turned off successfully
04/11/2016 03:13:39 PM - INFO - GUI display widget values succesfully restored.
04/11/2016 03:13:39 PM - INFO - Turning off sta3800 controller.
04/11/2016 03:13:39 PM - INFO - Controller turned off successfully.
04/11/2016 03:13:39 PM - INFO - Turning on sta3800 controller.
04/11/2016 03:13:39 PM - INFO - Controller turned on successfully.
04/11/2016 03:13:53 PM - INFO - Starting 4.0s Exposure image with filebase Hello.exp.4.0s.
04/11/2016 03:13:53 PM - ERROR - Executable exp_acq. not found. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 189, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 112, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
04/11/2016 03:13:56 PM - INFO - Turning off sta3800 controller
04/11/2016 03:13:56 PM - INFO - Controller turned off successfully
