2016-03-30 17:16:24,120 INFO     Logger initialized
2016-03-31 17:00:22,334 INFO     Logger initialized
03/31/2016 05:01:16 PM INFO     Logger initialized
03/31/2016 05:04:13 PM INFO     Logger initialized
03/31/2016 05:09:50 PM - INFO - Logger initialized
03/31/2016 05:09:55 PM - INFO - Turning off sta3800 controller
03/31/2016 05:09:55 PM - INFO - Controller turned off successfully
03/31/2016 05:28:52 PM - INFO - Logger initialized
03/31/2016 05:28:53 PM - INFO - Turning off sta3800 controller.
03/31/2016 05:28:53 PM - ERROR - Unable to turn off controller! State may be unknown.
03/31/2016 06:10:06 PM - INFO - Logger initialized
03/31/2016 06:10:07 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:10:07 PM - ERROR - Unable to turn off controller! State may be unknown.
03/31/2016 06:10:07 PM - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 81, in reset
    sta3800off_output = ccdsetup.sta3800_off()
  File "/Users/adamsnyder/ccdcontroller/ccdsetup.py", line 229, in sta3800_off
    output = subprocess.check_output("sta3800_off")
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
03/31/2016 06:35:13 PM - INFO - Logger initialized
03/31/2016 06:35:13 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:35:13 PM - ERROR - Unable to turn off controller! State may be unknown.
03/31/2016 06:35:13 PM - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 93, in reset
    sta3800off_output = ccdsetup.sta3800_off()
  File "/Users/adamsnyder/ccdcontroller/ccdsetup.py", line 229, in sta3800_off
    output = subprocess.check_output("sta3800_off")
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
03/31/2016 06:35:49 PM - INFO - Logger initialized
03/31/2016 06:35:49 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:36:08 PM - INFO - Logger initialized
03/31/2016 06:36:09 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:36:09 PM - INFO - Controller turned off successfully.
03/31/2016 06:36:09 PM - INFO - Turning on sta3800 controller.
03/31/2016 06:36:09 PM - INFO - Controller turned on successfully.
03/31/2016 06:36:14 PM - INFO - Starting 4.0s exp image with filebase Hello.exp.4.0s.
03/31/2016 06:36:42 PM - INFO - Turning off sta3800 controller
03/31/2016 06:36:42 PM - INFO - Controller turned off successfully
03/31/2016 06:42:59 PM - INFO - Logger initialized
03/31/2016 06:42:59 PM - INFO - Turning off sta3800 controller.
03/31/2016 06:42:59 PM - ERROR - Unable to turn off controller! State may be unknown.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 93, in reset
    raise OSError
OSError
